import type {Metadata} from "next";
import {Poppins} from "next/font/google";

import "./globals.css";
import {ReactNode} from "react";
import {initialSnackbarState, SnackbarProvider} from "@/context/snackbar";

const poppins = Poppins({
    variable: '--font-poppins',
    subsets: ['latin'],
    weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${poppins.variable}`}>
        <SnackbarProvider initialState={initialSnackbarState}>{children}</SnackbarProvider>
        </body>
        </html>
    );
}
